import Header from "./Header/Header";
import Intro from "./Intro/Intro";
import Quote from "./Quote";
import ProjectCard from "./ProjectCard/ProjectCard";
import SkillCard from "./SkillCard";
import AboutMe from "./AboutMe/AboutMe";
import ContactMe from "./ContactMe/ContactMe";
import Footer from "./Footer/Footer";
import Skills from "./Skills/Skills";
export {Header, Intro, Quote, ProjectCard, SkillCard, AboutMe, ContactMe, Footer, Skills};