import Header from "./Header";
import Intro from "./Intro";
import Quote from "./Quote";
import ProjectCard from "./ProjectCard";
import SkillCard from "./SkillCard";
import AboutMe from "./AboutMe";
import ContactMe from "./ContactMe";
import Footer from "./Footer";
import Skills from "./Skills";
export {Header, Intro, Quote, ProjectCard, SkillCard, AboutMe, ContactMe, Footer, Skills};